name: Build and Deploy Blazor Client

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Agregar host a known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Preparar directorio y copiar archivos
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} '
            mkdir -p /var/www/toros.salazarcode.net/src &&
            chmod -R 755 /var/www/toros.salazarcode.net
          '
          # Copiamos todo el código fuente a una carpeta src
          rsync -avz --delete \
            --exclude '.git' \
            --exclude 'bin' \
            --exclude 'obj' \
            ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/var/www/toros.salazarcode.net/src/

      - name: Build y Deploy Docker
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} '
            cd /var/www/toros.salazarcode.net/src &&
            docker build -t toros-client . &&
            docker stop toros-client || true &&
            docker rm toros-client || true &&
            docker run -d \
              --name toros-client \
              -p 5001:80 \
              --restart always \
              toros-client
          '

      - name: Limpiar imágenes antiguas
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} 'docker system prune -f'
