name: Build and Deploy Blazor Client
on:
  push:
    branches:
      - master
env:
  DEPLOY_PATH: /var/www/toros.salazarcode.com

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish --configuration Release --no-build --output ./publish

      - name: Configurar SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Agregar host a known_hosts
        run: ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Preparar directorio de despliegue con sudo
        run: |
          ssh deploy@${{ secrets.SERVER_HOST }} "
            sudo mkdir -p ${{ env.DEPLOY_PATH }} &&
            sudo chown -R deploy:deploy ${{ env.DEPLOY_PATH }} &&
            sudo chmod -R 755 ${{ env.DEPLOY_PATH }}
          "

      - name: Desplegar archivos estáticos
        run: |
          rsync -avz --delete \
            ./publish/wwwroot/ \
            deploy@${{ secrets.SERVER_HOST }}:${{ env.DEPLOY_PATH }}/

      - name: Verificar despliegue
        run: |
          ssh deploy@${{ secrets.SERVER_HOST }} "
            if [ ! -f ${{ env.DEPLOY_PATH }}/index.html ]; then
              echo 'No se encontró index.html en el directorio de despliegue'
              exit 1
            fi
          "